// <auto-generated />
#nullable enable
namespace WebApi.Models
{
    public partial class CarMapper
    {
        public partial global::WebApi.Models.CarDto ToCarDto(global::WebApi.Models.Car car)
        {
            var target = new global::WebApi.Models.CarDto();
            if (car.RegistrationNumber != null)
            {
                target.RegistrationNumber = car.RegistrationNumber;
            }
            if (car.Name != null)
            {
                target.Name = car.Name;
            }
            target.Id = car.Id;
            target.Created = car.Created;
            target.Vin = car.Vin;
            target.DoesVinAndRegistrationNumberMatches = car.DoesVinAndRegistrationNumberMatches;
            target.SeatsCount = car.SeatsCount;
            return target;
        }
    }
}