// <auto-generated />
#nullable enable
namespace WebApi.Models.DriverServiceModels
{
    public partial class PersonMapper
    {
        public partial global::WebApi.PersonData MapToPersonData(global::WebApi.Models.DriverServiceModels.Person person)
        {
            var target = new global::WebApi.PersonData();
            target.PassportSeries = person.PassportSeries;
            target.PassportNumber = person.PassportNumber;
            target.FirstName = person.FirstName;
            target.LastName = person.LastName;
            target.SecondName = person.SecondName;
            target.BirthDate = person.BirthDate;
            return target;
        }
    }
}