// <auto-generated />
#nullable enable
namespace WebApi.Models
{
    public partial class PriceDtoMapper
    {
        private partial void ToDtoAuto(global::WebApi.Models.Price entity, global::WebApi.Models.PriceDto dto)
        {
            dto.Id = entity.Id;
            dto.PriceInRub = entity.PriceInRub;
            dto.StartLegId = entity.StartLegId;
            dto.EndLegId = entity.EndLegId;
        }

        private partial void FromDtoAuto(global::WebApi.Models.PriceDto entity, global::WebApi.Models.Price leg)
        {
            leg.Id = entity.Id;
            leg.PriceInRub = entity.PriceInRub;
            leg.StartLegId = entity.StartLegId;
            leg.EndLegId = entity.EndLegId;
        }

        private partial void BetweenDtosAuto(global::WebApi.Models.PriceDto from, global::WebApi.Models.PriceDto to)
        {
            to.Id = from.Id;
            to.PriceInRub = from.PriceInRub;
            to.StartLegId = from.StartLegId;
            to.StartLeg = from.StartLeg;
            to.EndLegId = from.EndLegId;
            to.EndLeg = from.EndLeg;
        }

        private partial void BetweenEntitiesAuto(global::WebApi.Models.Price from, global::WebApi.Models.Price to)
        {
            to.Id = from.Id;
            to.PriceInRub = from.PriceInRub;
            to.StartLegId = from.StartLegId;
            to.StartLeg = from.StartLeg;
            to.EndLegId = from.EndLegId;
            to.EndLeg = from.EndLeg;
        }
    }
}