// <auto-generated />
#nullable enable
namespace WebApi
{
    public partial class RecommendedPriceDtoMapper
    {
        public partial global::WebApi.RecommendedPrice FromDto(global::WebApi.RecommendedPriceDto dto)
        {
            var target = new global::WebApi.RecommendedPrice();
            target.Low = dto.Low;
            target.Average = dto.Average;
            target.High = dto.High;
            target.Step = dto.Step;
            return target;
        }

        public partial global::WebApi.RecommendedPriceDto ToDto(global::WebApi.RecommendedPrice price)
        {
            var target = new global::WebApi.RecommendedPriceDto();
            target.Low = price.Low;
            target.Average = price.Average;
            target.High = price.High;
            target.Step = price.Step;
            return target;
        }
    }
}