// <auto-generated />
#nullable enable
namespace WebApi.Models
{
    public partial class ReservationMapper
    {
        public partial global::WebApi.Models.ReservationDto ToDto(global::WebApi.Models.Reservation reservation)
        {
            var target = new global::WebApi.Models.ReservationDto();
            target.Id = reservation.Id;
            target.RideId = reservation.RideId;
            target.PassengerId = reservation.PassengerId;
            target.PeopleCount = reservation.PeopleCount;
            target.Created = reservation.Created;
            return target;
        }
    }
}