// <auto-generated />
#nullable enable
namespace WebApi.Models
{
    public partial class RideCountsMapper
    {
        private partial void ToCounts(global::WebApi.Models.RideDbCounts src, global::WebApi.Models.RideCounts target)
        {
            target.TotalCount = src.TotalCount;
        }
    }
}