// <auto-generated />
#nullable enable
namespace WebApi.Models
{
    public partial class RideDtoMapper
    {
        public partial void FromDto(global::WebApi.Models.RideDto from, global::WebApi.Models.Ride to)
        {
            to.Id = from.Id;
            to.DriverId = from.DriverId;
        }

        public partial void ToDto(global::WebApi.Models.Ride from, global::WebApi.Models.RideDto to)
        {
            to.Id = from.Id;
            to.DriverId = from.DriverId;
        }
    }
}