// <auto-generated />
#nullable enable
namespace WebApi.Models
{
    public partial class RideDtoMapper
    {
        private partial void ToRide(global::WebApi.Models.RideDto src, global::WebApi.Models.Ride target)
        {
            target.Id = src.Id;
            target.AuthorId = src.AuthorId;
            target.DriverId = src.DriverId;
            target.CarId = src.CarId;
            target.Created = src.Created;
            target.Status = src.Status;
            target.AvailablePlacesCount = src.AvailablePlacesCount;
            target.Comment = src.Comment;
            target.ValidationMethod = src.ValidationMethod;
            target.ValidationTimeBeforeDeparture = src.ValidationTimeBeforeDeparture;
            target.AfterRideValidationTimeoutAction = src.AfterRideValidationTimeoutAction;
        }

        private partial void ToDtoAuto(global::WebApi.Models.Ride_Obsolete ride, global::WebApi.Models.RideDto_Obsolete dto)
        {
            dto.Status = ride.Status;
            dto.Id = ride.Id;
            dto.DriverId = ride.DriverId;
            dto.AvailablePlacesCount = ride.AvailablePlacesCount;
        }

        private partial void FromDtoAuto(global::WebApi.Models.RideDto_Obsolete dto, global::WebApi.Models.Ride_Obsolete ride)
        {
            ride.Id = dto.Id;
            ride.DriverId = dto.DriverId;
            ride.AvailablePlacesCount = dto.AvailablePlacesCount;
            ride.Status = dto.Status;
        }

        private partial void BetweenDtosAuto(global::WebApi.Models.RideDto_Obsolete from, global::WebApi.Models.RideDto_Obsolete to)
        {
            to.Prices = from.Prices;
            to.Status = from.Status;
            to.Id = from.Id;
            to.DriverId = from.DriverId;
            to.Legs = from.Legs;
            to.AvailablePlacesCount = from.AvailablePlacesCount;
        }

        private partial void BetweenEntitiesAuto(global::WebApi.Models.Ride_Obsolete from, global::WebApi.Models.Ride_Obsolete to)
        {
            to.Id = from.Id;
            to.DriverId = from.DriverId;
            to.AvailablePlacesCount = from.AvailablePlacesCount;
            to.Status = from.Status;
        }
    }
}