// <auto-generated />
#nullable enable
namespace WebApi.Models
{
    public partial class SearchRideResponseMapper
    {
        private partial void MapToResponse(global::WebApi.Models.SearchRideDbResponse source, global::WebApi.Models.RideDto target)
        {
            target.Id = source.RideId;
            target.AuthorId = source.AuthorId;
            target.DriverId = source.DriverId;
            target.Created = source.Created;
            target.AvailablePlacesCount = source.TotalAvailablePlacesCount;
            target.ValidationMethod = source.ValidationMethod;
            target.ValidationTimeBeforeDeparture = source.ValidationTimeBeforeDeparture;
            target.AfterRideValidationTimeoutAction = source.AfterRideValidationTimeoutAction;
        }

        private partial void MapToResponse(global::WebApi.Models.SearchRideDbResponse source, global::WebApi.Models.SearchRideResponse target)
        {
            target.DepartureDistanceKilometers = source.FromDistanceKilometers;
            target.ArrivalDistanceKilometers = source.ToDistanceKilometers;
            target.PriceInRub = source.Price;
        }
    }
}