// <auto-generated />
#nullable enable
namespace WebApi.Models
{
    public partial class WaypointMapper
    {
        private partial global::WebApi.Models.Waypoint ToWaypoint(global::WebApi.Models.WaypointDto dto)
        {
            var target = new global::WebApi.Models.Waypoint();
            target.Point = (global::NetTopologySuite.Geometries.Point)dto.Point;
            target.FullName = dto.FullName;
            target.NameToCity = dto.NameToCity;
            target.Arrival = dto.Arrival;
            target.Departure = dto.Departure;
            return target;
        }
    }
}