// <auto-generated />
#nullable enable
namespace WebApi.Models
{
    public partial class YandexGeocodeResponseDtoMapper
    {
        private partial void ToDtoAuto(global::WebApi.Models.YandexGeocodeResponse entity, global::WebApi.Models.YandexGeocodeResponseDto dto)
        {
            dto.Success = entity.Success;
        }
    }
}