// <auto-generated />
#nullable enable
namespace WebApi.Models
{
    public partial class YandexSuggestResponseDtoMapper
    {
        private partial void ToDtoAuto(global::WebApi.Models.YandexSuggestResponse entity, global::WebApi.Models.YandexSuggestResponseDto dto)
        {
            dto.Success = entity.Success;
        }

        private partial void BetweenDtosAuto(global::WebApi.Models.YandexSuggestResponseDto from, global::WebApi.Models.YandexSuggestResponseDto to)
        {
            to.Results = from.Results;
            to.Success = from.Success;
        }
    }
}