// <auto-generated />
#nullable enable
namespace WebApi.Models
{
    public partial class YandexGeocodeResponseDtoMapper
    {
        private partial void ToDtoAuto(global::WebApi.Models.YandexGeocodeResponse entity, global::WebApi.Models.YandexGeocodeResponseDto dto)
        {
            dto.Success = entity.Success;
        }

        private partial void BetweenDtosAuto(global::WebApi.Models.YandexGeocodeResponseDto from, global::WebApi.Models.YandexGeocodeResponseDto to)
        {
            to.Success = from.Success;
            to.Geoobjects = from.Geoobjects;
        }
    }
}