// <auto-generated />
#nullable enable
namespace WebApi.Models
{
    public partial class YandexSuggestResponseDtoMapper
    {
        private partial void ToDtoAuto(global::WebApi.Models.YandexSuggestResponse entity, global::WebApi.Models.YandexSuggestResponseDto dto)
        {
            dto.Success = entity.Success;
        }
    }
}