// <auto-generated />
#nullable enable
namespace WebApi.Models
{
    public partial class YandexSuggestResponseDtoResultMapper
    {
        private partial void ToDtoAuto(global::WebApi.Models.YandexSuggestResponse.Result entity, global::WebApi.Models.YandexSuggestResponseDto.YandexSuggestResponseDtoResult dto)
        {
            dto.Uri = entity.Uri;
        }

        private partial void BetweenDtosAuto(global::WebApi.Models.YandexSuggestResponseDto.YandexSuggestResponseDtoResult from, global::WebApi.Models.YandexSuggestResponseDto.YandexSuggestResponseDtoResult to)
        {
            to.FormattedAddress = from.FormattedAddress;
            to.Title = from.Title;
            to.SubTitle = from.SubTitle;
            to.Uri = from.Uri;
        }
    }
}