// <auto-generated />
#nullable enable
namespace WebApi.Models
{
    public partial class YandexGeocodeResponseGeoobjectDtoMapper
    {
        private partial void BetweenDtosAuto(global::WebApi.Models.YandexGeocodeResponseDto.YandexGeocodeResponseGeoobjectDto from, global::WebApi.Models.YandexGeocodeResponseDto.YandexGeocodeResponseGeoobjectDto to)
        {
            to.FormattedAddress = from.FormattedAddress;
            to.Point = from.Point;
        }
    }
}