// <auto-generated />
#nullable enable
namespace WebApi.Models
{
    public partial class YandexSuggestResponseDtoResultMapper
    {
        private partial void ToDtoAuto(global::WebApi.Models.YandexSuggestResponse.Result entity, global::WebApi.Models.YandexSuggestResponseDto.YandexSuggestResponseDtoResult dto)
        {
            dto.Uri = entity.Uri;
        }
    }
}