version: '3.8'

services:
  redis:
    image: redis:7.2.3
    volumes:
      - ${BBC_REDIS_DATA_PATH:-C:/bbc/redis}:/data
    networks:
      - bbc
    ports:
      - 6379:6379
    entrypoint: redis-server --maxmemory-policy volatile-lru --maxmemory 1gb
    deploy:
      resources:
        limits:
          memory: 1536M

  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_PASSWORD: postgres
    # volumes:
    #   - C:/bbc/postgres/backups:/backups
    networks:
      - bbc
    ports:
      - 5432:5432
    # expose:
    #   - "5432"

  seq:
    image: datalust/seq:2023.4
    ports:
      - 81:80
      - 5341:5341
    volumes:
      - ${BBC_SEQ_DATA_PATH:-/c/bbc/seq}:/data
    environment:
      - ACCEPT_EULA=Y
    networks:
      - bbc
  # api:
  #   build: ./  # путь к Dockerfile
  #   ports:
  #     - "80:80"
  #   networks:
  #     - bbc

networks:
  bbc:
    driver: bridge
